### ISSUE TITLE
Дописать ТЗ

### ISSUE THREAD

**Issue by wldmr-key** [romankuz19/web-application#1]
Характеристика предметной области и вменяемые функциональные характеристики

В Issues обсуждаются частные вопросы - это правильнее, чем в почте

**Comment by romankuz19** [comment]
Окей, спасибо! Буду дорабатывать

**Comment by romankuz19** [comment]
Здравствуйте еще раз, дописал характеристику предметной области и функциональные характеристики в ТЗ. Залил новую версию в документацию.
